use car_sales ;

--1-What are the details of all cars purchased in the year 2022?
select * from 
cars c left join sales s
on c.car_id = s.car_id
where YEAR  (purchase_date) = 2022 ;

--2-What is the total number of cars sold by each salesperson?
select p.salesman_id , p.name , count( car_id) as total_sales
from salespersons p join sales s 
on p.salesman_id = s.salesman_id 
group by  p.salesman_id , p.name
order by total_sales ;

--3-What is the total revenue generated by each salesperson?
select p.salesman_id , p.name , sum(cost_$) as total
from salespersons p join sales s 
on p.salesman_id = s.salesman_id 
join cars c
on c.car_id =s.car_id 
group by p.salesman_id , p.name ;

--4-What are the details of the cars sold by each salesperson?
select p.salesman_id , p.name , c.car_id ,c.style ,c.type ,c.cost_$
from salespersons p join sales s 
on p.salesman_id = s.salesman_id 
join cars c
on c.car_id =s.car_id ;

--5-What is the total revenue generated by each car type?
select c.type,sum(cost_$) as total
from  sales s join cars c
on c.car_id =s.car_id 
group by c.type ;

--6- What are the details of the cars sold in the year 2021 by salesperson ‘Emily Wong’?
select p.salesman_id , p.name , c.car_id ,c.style ,c.type ,c.cost_$
from salespersons p join sales s 
on p.salesman_id = s.salesman_id 
join cars c
on c.car_id =s.car_id
where p.name = 'Emily Wong'  and YEAR  (purchase_date) = 2021;

--7. What is the total revenue generated by the sales of hatchback cars?
select c.style,sum(cost_$) as total
from  sales s join cars c
on c.car_id =s.car_id 
where c.style = 'hatchback'
group by c.style ;

--8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select c.style,sum(cost_$) as total
from  sales s join cars c
on c.car_id =s.car_id 
where c.style = 'SUV'
and YEAR(s.purchase_date) =2022
group by c.style ;
--9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select top 1 p.salesman_id , p.name , count( car_id) as total_sales
from salespersons p join sales s 
on p.salesman_id = s.salesman_id 
where
YEAR(s.purchase_date) =2023
group by  p.salesman_id , p.name
order by total_sales desc ;

--10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
with cte as (

select top 1  p.name ,p.age , sum( c.cost_$) as total_sales
from 
salespersons p join sales s 
on p.salesman_id = s.salesman_id 
join cars c on c.car_id = s.car_id
where
YEAR(s.purchase_date) =2022
group by  p.age , p.name
order by total_sales desc 
)
select * 
from cte ;